### ISSUE TITLE
Dockerfile not available

### ISSUE THREAD

**Issue by LennyM8472** [foxylion/docker-steam-csgo#1]
Hi,

would really appreciate that this docker container is available https://hub.docker.com/r/foxylion/steam-csgo/builds/

thanks
Lenny

**Comment by foxylion** [comment]
Hi Lenny,
there is a problem with the Docker-Hub. It does not support such big images (more then 10G for a single layer). So you've to build in manually on your server (is not that hard):

```
$ git clone https://github.com/foxylion/docker-steam-csgo.git
$ cd docker-steam-csgo
$ docker build -t foxylion/steam-csgo .
```

Then call `docker run ..` (similar to the [README](https://github.com/foxylion/docker-steam-csgo#start-the-container)).

Regards,
Jakob
